<?php
$pageTitle='Oversized T-Shirts'; require 'includes/header.php'; require 'includes/navbar.php';
$pdo=db();
$new=$pdo->query("SELECT * FROM products WHERE status='active' ORDER BY created_at DESC LIMIT 4")->fetchAll();
$trending=$pdo->query("SELECT * FROM products WHERE status='active' ORDER BY sales_count DESC LIMIT 4")->fetchAll();
$deals=$pdo->query("SELECT * FROM products WHERE status='active' AND discount_percent>0 ORDER BY discount_percent DESC LIMIT 4")->fetchAll();
$categories=$pdo->query('SELECT * FROM categories LIMIT 6')->fetchAll();
function home_cards($items){ foreach($items as $p){ $price=product_price($p); ?> <div class="col-6 col-md-3"><div class="card product-card"><img class="product-image" src="<?=base(e($p['image']))?>" alt="<?=e($p['name'])?>"><div class="card-body"><small class="text-muted"><?=e($p['brand'])?></small><h6 class="mt-1"><?=e($p['name'])?></h6><span class="fw-bold"><?=money($price)?></span><?php if($p['discount_percent']): ?> <small class="price-old ms-1"><?=money($p['original_price'])?></small><?php endif ?><br><a class="btn btn-dark btn-sm mt-3" href="<?=base('product-details.php?id='.$p['id'])?>">View Tee</a></div></div></div><?php }} ?>
<section id="hero" class="carousel slide" data-bs-ride="carousel"><div class="carousel-indicators"><button data-bs-target="#hero" data-bs-slide-to="0" class="active"></button><button data-bs-target="#hero" data-bs-slide-to="1"></button><button data-bs-target="#hero" data-bs-slide-to="2"></button></div><div class="carousel-inner"><div class="carousel-item active"><div class="hero-slide"><div class="container"><p class="tracking text-white-50">OVERSO / 01</p><h1 class="hero-title">OVERSIZED.<br>ORIGINAL.<br>YOURS.</h1><a class="btn btn-light btn-lg mt-4" href="<?=base('products.php')?>">SHOP OVERSIZED</a></div></div></div><div class="carousel-item"><div class="hero-slide alt"><div class="container"><p class="tracking text-white-50">OVERSO / 02</p><h2 class="hero-title">NEW<br>DROP</h2><p class="fs-5">Fresh oversized T-shirts made for everyday streetwear.</p><a class="btn btn-light btn-lg" href="<?=base('products.php?sort=newest')?>">EXPLORE NEW DROP</a></div></div></div><div class="carousel-item"><div class="hero-slide deal"><div class="container"><p class="tracking text-white-50">OVERSO / 03</p><h2 class="hero-title">UP TO<br>50% OFF</h2><p class="fs-5">Upgrade your oversized collection.</p><a class="btn btn-light btn-lg" href="<?=base('products.php?discount=20')?>">SHOP DEALS</a></div></div></div></div><button class="carousel-control-prev" data-bs-target="#hero" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span></button><button class="carousel-control-next" data-bs-target="#hero" data-bs-slide="next"><span class="carousel-control-next-icon"></span></button></section>
<main class="container my-5"><section><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="section-title">Shop by collection</h2><a href="<?=base('products.php')?>" class="text-dark">View all</a></div><div class="row g-3"><?php foreach($categories as $c): ?><div class="col-6 col-md-4"><a class="collection" style="background-image:linear-gradient(#0003,#0007),url('<?=e(base($c['image']))?>');background-size:cover;background-position:center;color:#fff;text-shadow:0 1px 4px #000" href="<?=base('products.php?category='.$c['id'])?>"><?=e(str_replace(' Oversized','',$c['name']))?></a></div><?php endforeach ?></div></section><section class="mt-5"><h2 class="section-title mb-3">New drops</h2><div class="row g-3"><?php home_cards($new) ?></div></section><section class="mt-5"><h2 class="section-title mb-3">Trending oversized T-shirts</h2><div class="row g-3"><?php home_cards($trending) ?></div></section><section class="mt-5"><h2 class="section-title mb-3">Today's deals</h2><div class="row g-3"><?php home_cards($deals) ?></div></section><section class="mt-5 row g-3"><div class="col-md"><div class="p-4 bg-white h-100"><h2 class="section-title">Why OVERSO?</h2><p>Premium fabric, a true oversized fit, secure simulated checkout, fast delivery, and easy returns.</p></div></div><?php foreach(['Premium Fabric','Oversized Fit','Secure Checkout','Fast Delivery','Easy Returns'] as $benefit): ?><div class="col-6 col-md"><div class="p-3 border h-100"><b><?=e($benefit)?></b></div></div><?php endforeach ?></section></main><?php require 'includes/footer.php'; ?>
