<?php
$pageTitle='Shop'; require 'includes/header.php'; require 'includes/navbar.php'; $pdo=db(); $where=["p.status='active'"]; $params=[];
if(!empty($_GET['q'])){$where[]="CONCAT(p.name,' ',p.brand,' ',c.name,' ',p.description,' ',p.color) LIKE :term";$params[':term']='%'.trim($_GET['q']).'%';}
foreach(['category'=>'p.category_id','brand'=>'p.brand','color'=>'p.color'] as $input=>$field) if(!empty($_GET[$input])){$where[]="$field=:$input";$params[':'.$input]=$_GET[$input];}
if(!empty($_GET['size'])){$where[]='EXISTS (SELECT 1 FROM product_sizes fs WHERE fs.product_id=p.id AND fs.size=:size AND fs.stock_quantity>0)';$params[':size']=$_GET['size'];}
if(!empty($_GET['min'])){$where[]='(p.original_price*(100-p.discount_percent)/100)>=:min';$params[':min']=(float)$_GET['min'];}
if(!empty($_GET['max'])){$where[]='(p.original_price*(100-p.discount_percent)/100)<=:max';$params[':max']=(float)$_GET['max'];}
if(!empty($_GET['rating'])){$where[]='p.rating>=:rating';$params[':rating']=(float)$_GET['rating'];}
if(isset($_GET['availability'])&&$_GET['availability']==='in')$where[]='p.stock_quantity>0'; if(!empty($_GET['discount'])){$where[]='p.discount_percent>=:discount';$params[':discount']=(float)$_GET['discount'];}
$sorts=['price_asc'=>'final_price ASC','price_desc'=>'final_price DESC','newest'=>'p.created_at DESC','popular'=>'p.sales_count DESC','rated'=>'p.rating DESC','discount'=>'p.discount_percent DESC'];$order=$sorts[$_GET['sort']??'newest']??'p.created_at DESC';
$sql='SELECT p.*,c.name category_name,GROUP_CONCAT(ps.size ORDER BY FIELD(ps.size,"S","M","L","XL","XXL","XXXL")) sizes FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN product_sizes ps ON ps.product_id=p.id AND ps.stock_quantity>0 WHERE '.implode(' AND ',$where).' GROUP BY p.id ORDER BY '.str_replace('final_price','(p.original_price*(100-p.discount_percent)/100)',$order);
$st=$pdo->prepare($sql);$st->execute($params);$products=$st->fetchAll();$categories=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();$brands=$pdo->query('SELECT DISTINCT brand FROM products ORDER BY brand')->fetchAll();
?>
<main class="container my-4"><div class="d-flex justify-content-between align-items-center"><div><p class="text-muted mb-1">OVERSIZED T-SHIRTS ONLY</p><h1 class="section-title">Shop OVERSO</h1></div><span><?=count($products)?> Oversized T-Shirts Found</span></div><form class="filter-box p-3 my-4 row g-2"><div class="col-md-3"><input class="form-control" name="q" value="<?=e($_GET['q']??'')?>" placeholder="Search tees, brand, colour..."></div><div class="col-md"><select class="form-select" name="category"><option value="">Collection</option><?php foreach($categories as $c): ?><option value="<?=$c['id']?>" <?=($_GET['category']??'')==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach ?></select></div><div class="col-md"><select class="form-select" name="size"><option value="">Size</option><?php foreach(['S','M','L','XL','XXL','XXXL'] as $s): ?><option <?=($_GET['size']??'')===$s?'selected':''?>><?=$s?></option><?php endforeach ?></select></div><div class="col-md"><input type="number" class="form-control" name="min" placeholder="Min price" value="<?=e($_GET['min']??'')?>"></div><div class="col-md"><input type="number" class="form-control" name="max" placeholder="Max price" value="<?=e($_GET['max']??'')?>"></div><div class="col-md"><select class="form-select" name="sort"><option value="newest">Newest</option><?php foreach(['price_asc'=>'Price: low to high','price_desc'=>'Price: high to low','popular'=>'Popular','rated'=>'Highest rated','discount'=>'Biggest discount'] as $v=>$l): ?><option value="<?=$v?>" <?=($_GET['sort']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach ?></select></div><div class="col-md-auto"><button class="btn btn-dark w-100">Apply</button></div></form><div class="row g-3"><?php foreach($products as $p): $price=product_price($p); ?><div class="col-6 col-md-4 col-lg-3"><div class="card product-card"><a href="<?=base('product-details.php?id='.$p['id'])?>"><img class="product-image" src="<?=base(e($p['image']))?>" alt="<?=e($p['name'])?>"></a><div class="card-body"><div class="d-flex justify-content-between"><small><?=e($p['brand'])?></small><?php if($p['discount_percent']): ?><span class="badge badge-lime"><?=$p['discount_percent']?>% OFF</span><?php endif ?></div><h6 class="mt-2 mb-1"><?=e($p['name'])?></h6><small class="text-warning">★ <?=$p['rating']?> (<?=$p['review_count']?>)</small><p class="mb-1 fw-bold"><?=money($price)?> <span class="price-old small"><?=money($p['original_price'])?></span></p><small><?=e($p['sizes']?:'Unavailable')?></small><div class="d-flex gap-2 mt-3"><a class="btn btn-dark btn-sm" href="<?=base('product-details.php?id='.$p['id'])?>">View Details</a><a class="btn btn-outline-dark btn-sm" href="<?=base('wishlist.php?action=add&id='.$p['id'])?>">♡</a></div></div></div></div><?php endforeach ?></div><?php if(!$products): ?><div class="alert alert-secondary">No oversized T-shirts match these filters.</div><?php endif ?></main><?php require 'includes/footer.php'; ?>
