CREATE DATABASE IF NOT EXISTS overso CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE overso;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS recently_viewed, reviews, payments, order_items, orders, coupon_usage, coupons, addresses, wishlist, cart, product_sizes, products, categories, admins, users;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(120) NOT NULL UNIQUE, mobile VARCHAR(15) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, address TEXT, profile_image VARCHAR(255) DEFAULT NULL, status ENUM('blocked','active') NOT NULL DEFAULT 'blocked', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(status));
CREATE TABLE admins (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(255), image VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, category_id INT NOT NULL, name VARCHAR(150) NOT NULL, brand VARCHAR(80) NOT NULL DEFAULT 'OVERSO', description TEXT NOT NULL, specifications TEXT, material VARCHAR(80) DEFAULT '240 GSM Cotton', fit_type VARCHAR(80) DEFAULT 'Relaxed Oversized Fit', color VARCHAR(50) NOT NULL, original_price DECIMAL(10,2) NOT NULL, discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0, image VARCHAR(255) DEFAULT 'assets/images/products/tee.svg', additional_images TEXT, stock_quantity INT NOT NULL DEFAULT 0, sales_count INT DEFAULT 0, rating DECIMAL(3,2) DEFAULT 0, review_count INT DEFAULT 0, status ENUM('active','inactive','out_of_stock','discontinued') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES categories(id), INDEX(category_id), INDEX(status), INDEX(color));
CREATE TABLE product_sizes (id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, size ENUM('S','M','L','XL','XXL','XXXL') NOT NULL, stock_quantity INT NOT NULL DEFAULT 0, UNIQUE KEY product_size(product_id,size), FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE cart (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,product_id INT NOT NULL,size VARCHAR(10) NOT NULL,quantity INT NOT NULL DEFAULT 1, UNIQUE KEY user_product_size(user_id,product_id,size),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE wishlist (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,product_id INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY user_product(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE addresses (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,full_name VARCHAR(100) NOT NULL,mobile VARCHAR(15) NOT NULL,address TEXT NOT NULL,city VARCHAR(60) NOT NULL,state VARCHAR(60) NOT NULL,pincode VARCHAR(10) NOT NULL,is_default TINYINT(1) DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE coupons (id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) NOT NULL UNIQUE,discount_type ENUM('percent','flat') NOT NULL,discount_value DECIMAL(10,2) NOT NULL,minimum_order DECIMAL(10,2) DEFAULT 0,maximum_discount DECIMAL(10,2) DEFAULT NULL,expiry_date DATE NOT NULL,usage_limit INT DEFAULT 100,used_count INT DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active');
CREATE TABLE coupon_usage (id INT AUTO_INCREMENT PRIMARY KEY,coupon_id INT NOT NULL,user_id INT NOT NULL,order_id INT NULL,used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(coupon_id) REFERENCES coupons(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE orders (id INT AUTO_INCREMENT PRIMARY KEY,order_number VARCHAR(30) UNIQUE NOT NULL,user_id INT NOT NULL,coupon_id INT NULL,shipping_address TEXT NOT NULL,billing_address TEXT NOT NULL,subtotal DECIMAL(10,2) NOT NULL,coupon_discount DECIMAL(10,2) DEFAULT 0,tax DECIMAL(10,2) DEFAULT 0,delivery_charge DECIMAL(10,2) DEFAULT 0,total_amount DECIMAL(10,2) NOT NULL,payment_method ENUM('cod','upi','card','netbanking') NOT NULL,payment_status ENUM('pending','paid','failed') DEFAULT 'pending',order_status ENUM('pending','confirmed','packed','shipped','out_for_delivery','delivered','cancelled') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(coupon_id) REFERENCES coupons(id),INDEX(order_status));
CREATE TABLE order_items (id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,product_id INT NOT NULL,product_name VARCHAR(150) NOT NULL,size VARCHAR(10) NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(10,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE payments (id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL UNIQUE,method VARCHAR(20) NOT NULL,amount DECIMAL(10,2) NOT NULL,status ENUM('pending','paid','failed') DEFAULT 'pending',transaction_ref VARCHAR(60),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE reviews (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,product_id INT NOT NULL,rating TINYINT NOT NULL,review_text TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY user_product_review(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE recently_viewed (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,product_id INT NOT NULL,viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY user_product_recent(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);

INSERT INTO admins(name,username,password) VALUES ('OVERSO Admin','admin','$2y$10$mEUa2zEpB1DOZJGFwj6vh.umfCPlR7vDqXIpHPzzTdBnRA8sMl4sG');
INSERT INTO users(full_name,username,email,mobile,password,address,status) VALUES ('Riya Sharma','riya','riya@overso.test','9876543210','$2y$10$CCqhyrn0sVr3NbzjgIL.vuezFIeWxWK8uO4MgX0bJ3Uart378QU1S','24 Park Street, Kolkata','active'),('Arjun Mehta','arjun','arjun@overso.test','9876543211','$2y$10$CCqhyrn0sVr3NbzjgIL.vuezFIeWxWK8uO4MgX0bJ3Uart378QU1S','18 MG Road, Bengaluru','blocked');
INSERT INTO categories(name,description,image) VALUES ('Graphic Oversized','Bold graphic-led oversized tees','assets/images/products/tee.svg'),('Minimal Oversized','Clean essentials with quiet detail','assets/images/products/tee.svg'),('Streetwear','Street-ready oversized silhouettes','assets/images/products/tee.svg'),('Typography','Tees with statement type','assets/images/products/tee.svg'),('Anime','Illustrated anime oversized tees','assets/images/products/tee.svg'),('Vintage','Washed, retro-inspired designs','assets/images/products/tee.svg'),('Plain','Premium plain oversized basics','assets/images/products/tee.svg'),('Drop Shoulder','Extra relaxed drop shoulder cuts','assets/images/products/tee.svg'),('Premium Cotton','Heavyweight premium cotton tees','assets/images/products/tee.svg'),('Oversized Printed','All-over and front printed tees','assets/images/products/tee.svg');
INSERT INTO products(category_id,name,brand,description,specifications,material,fit_type,color,original_price,discount_percent,stock_quantity,sales_count,rating,review_count,status) VALUES
(1,'Midnight Graffiti Oversized Tee','OVERSO','An oversized black graphic T-shirt designed for late-night city energy.','240 GSM; screen print; ribbed neck','240 GSM Cotton','Drop Shoulder Oversized','Black',1499,20,30,74,4.6,21,'active'),
(1,'Solar Sketch Oversized Tee','OVERSO','A warm-toned illustrated graphic tee for daily rotation.','220 GSM; screen print','220 GSM Cotton','Relaxed Oversized','Cream',1399,10,22,58,4.4,15,'active'),
(1,'Concrete Wave Oversized Tee','OVERSO','Abstract wave graphic on a charcoal oversized base.','240 GSM; puff print','240 GSM Cotton','Relaxed Oversized','Charcoal',1599,25,9,84,4.8,39,'active'),
(2,'Essential Ink Oversized Tee','OVERSO','The clean black oversized essential.','240 GSM; minimal chest mark','240 GSM Cotton','Relaxed Oversized','Black',1199,0,45,55,4.5,17,'active'),
(2,'Essential Bone Oversized Tee','OVERSO','A quiet off-white oversized staple.','240 GSM; tonal branding','240 GSM Cotton','Relaxed Oversized','White',1199,10,37,42,4.3,12,'active'),
(2,'Slate Line Oversized Tee','OVERSO','Minimal linework for an understated street silhouette.','220 GSM; embroidery','220 GSM Cotton','Relaxed Oversized','Grey',1299,15,5,21,4.2,8,'active'),
(3,'City Signal Oversized Tee','OVERSO','High-energy streetwear oversized print.','240 GSM; front and back print','240 GSM Cotton','Drop Shoulder Oversized','Black',1699,30,18,97,4.7,28,'active'),
(3,'Metro Fade Oversized Tee','OVERSO','Faded pigment wash with a street-ready cut.','260 GSM; garment washed','260 GSM Cotton','Drop Shoulder Oversized','Olive',1799,10,13,61,4.5,16,'active'),
(3,'Night Runner Oversized Tee','OVERSO','Reflective-inspired print on premium dark cotton.','240 GSM; reflective detail','240 GSM Cotton','Relaxed Oversized','Navy',1599,0,0,34,4.3,10,'out_of_stock'),
(4,'Speak Loud Oversized Tee','OVERSO','Statement typography in a confident oversized fit.','220 GSM; plastisol print','220 GSM Cotton','Relaxed Oversized','White',1299,20,20,80,4.6,22,'active'),
(4,'Offline Mode Oversized Tee','OVERSO','A downtime uniform with bold front typography.','240 GSM; screen print','240 GSM Cotton','Drop Shoulder Oversized','Black',1499,15,12,56,4.4,14,'active'),
(4,'Original Energy Oversized Tee','OVERSO','Core OVERSO message printed on heavyweight cotton.','260 GSM; raised print','260 GSM Cotton','Relaxed Oversized','Beige',1699,25,4,73,4.7,25,'active'),
(5,'Shonen Storm Oversized Tee','OVERSO','Dynamic anime-inspired art, made for oversized layering.','240 GSM; full colour print','240 GSM Cotton','Drop Shoulder Oversized','Black',1799,20,16,110,4.9,45,'active'),
(5,'Manga Panel Oversized Tee','OVERSO','Monochrome manga panel graphics on a white base.','220 GSM; digital print','220 GSM Cotton','Relaxed Oversized','White',1599,10,19,89,4.7,31,'active'),
(5,'Neon Hero Oversized Tee','OVERSO','Vibrant anime visual on charcoal cotton.','240 GSM; screen print','240 GSM Cotton','Drop Shoulder Oversized','Charcoal',1899,30,7,102,4.8,41,'active'),
(6,'Retro Radio Oversized Tee','OVERSO','Faded retro graphic with a lived-in feel.','240 GSM; pigment wash','240 GSM Cotton','Relaxed Oversized','Brown',1599,20,14,66,4.4,18,'active'),
(6,'Archive Club Oversized Tee','OVERSO','A collegiate vintage oversized T-shirt.','220 GSM; cracked print','220 GSM Cotton','Relaxed Oversized','Maroon',1499,10,17,49,4.2,11,'active'),
(6,'Old School Oversized Tee','OVERSO','Classic washed look with large back graphic.','260 GSM; acid wash','260 GSM Cotton','Drop Shoulder Oversized','Grey',1799,0,8,62,4.5,19,'active'),
(7,'Core Black Oversized Tee','OVERSO','Heavyweight plain black oversized tee.','260 GSM; pre-shrunk','260 GSM Cotton','Drop Shoulder Oversized','Black',1399,5,54,95,4.8,33,'active'),
(7,'Core White Oversized Tee','OVERSO','Heavyweight plain white oversized tee.','260 GSM; pre-shrunk','260 GSM Cotton','Drop Shoulder Oversized','White',1399,5,48,88,4.7,29,'active'),
(7,'Core Sand Oversized Tee','OVERSO','Warm neutral plain oversized essential.','240 GSM; pre-shrunk','240 GSM Cotton','Relaxed Oversized','Sand',1299,0,31,43,4.4,15,'active'),
(8,'Relaxed Ink Drop Shoulder','OVERSO','Extra-drop shoulder tee with subtle branding.','260 GSM; broad shoulder','260 GSM Cotton','Drop Shoulder Oversized','Black',1699,20,11,77,4.6,23,'active'),
(8,'Relaxed Moss Drop Shoulder','OVERSO','Earthy green tee cut generously through the shoulder.','260 GSM; broad shoulder','260 GSM Cotton','Drop Shoulder Oversized','Olive',1699,15,6,39,4.3,9,'active'),
(8,'Relaxed Fog Drop Shoulder','OVERSO','Cool grey drop-shoulder oversized tee.','240 GSM; broad shoulder','240 GSM Cotton','Drop Shoulder Oversized','Grey',1599,10,15,44,4.4,13,'active'),
(9,'Heavyweight Onyx Tee','OVERSO','Premium 300 GSM oversized black cotton tee.','300 GSM; combed cotton','300 GSM Combed Cotton','Drop Shoulder Oversized','Black',2199,10,10,64,4.8,26,'active'),
(9,'Heavyweight Ivory Tee','OVERSO','Premium ivory heavyweight oversized tee.','300 GSM; combed cotton','300 GSM Combed Cotton','Drop Shoulder Oversized','Ivory',2199,0,12,52,4.7,17,'active'),
(9,'Heavyweight Cobalt Tee','OVERSO','Rich cobalt premium cotton in an oversized cut.','280 GSM; combed cotton','280 GSM Combed Cotton','Relaxed Oversized','Blue',1999,25,3,47,4.5,12,'active'),
(10,'Chrome Grid Printed Tee','OVERSO','Silver grid printed oversized street T-shirt.','240 GSM; screen print','240 GSM Cotton','Relaxed Oversized','Black',1699,30,8,87,4.6,30,'active'),
(10,'Desert Bloom Printed Tee','OVERSO','Soft desert palette floral graphic in oversized form.','220 GSM; digital print','220 GSM Cotton','Relaxed Oversized','Beige',1599,20,16,53,4.3,16,'active'),
(10,'Signal Red Printed Tee','OVERSO','Statement red front print on clean white cotton.','240 GSM; screen print','240 GSM Cotton','Drop Shoulder Oversized','White',1699,15,2,38,4.2,8,'active');
UPDATE products SET image = CASE category_id
    WHEN 1 THEN 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85'
    WHEN 2 THEN 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=85'
    WHEN 3 THEN 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85'
    WHEN 4 THEN 'https://images.unsplash.com/photo-1509942774463-acf339cf87d5?auto=format&fit=crop&w=900&q=85'
    WHEN 5 THEN 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85'
    WHEN 6 THEN 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=85'
    WHEN 7 THEN 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=85'
    WHEN 8 THEN 'https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=900&q=85'
    WHEN 9 THEN 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=85'
    WHEN 10 THEN 'https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=900&q=85'
END;
INSERT INTO product_sizes(product_id,size,stock_quantity) SELECT p.id,s.size,CASE WHEN p.stock_quantity=0 THEN 0 WHEN s.size='XXXL' THEN FLOOR(p.stock_quantity/8) ELSE FLOOR(p.stock_quantity/5) END FROM products p CROSS JOIN (SELECT 'S' size UNION SELECT 'M' UNION SELECT 'L' UNION SELECT 'XL' UNION SELECT 'XXL' UNION SELECT 'XXXL') s;
INSERT INTO addresses(user_id,full_name,mobile,address,city,state,pincode,is_default) VALUES (1,'Riya Sharma','9876543210','24 Park Street','Kolkata','West Bengal','700016',1);
INSERT INTO coupons(code,discount_type,discount_value,minimum_order,maximum_discount,expiry_date,usage_limit,status) VALUES ('OVERSO20','percent',20,1000,500,'2027-12-31',100,'active'),('WELCOME150','flat',150,799,NULL,'2027-12-31',50,'active'),('EXPIRED10','percent',10,500,300,'2024-01-01',20,'active');
INSERT INTO orders(order_number,user_id,shipping_address,billing_address,subtotal,tax,delivery_charge,total_amount,payment_method,payment_status,order_status) VALUES ('OVR-202608-1001',1,'Riya Sharma, 24 Park Street, Kolkata, West Bengal - 700016','Riya Sharma, 24 Park Street, Kolkata, West Bengal - 700016',1199,59.95,0,1258.95,'card','paid','delivered');
INSERT INTO order_items(order_id,product_id,product_name,size,quantity,unit_price) VALUES (1,4,'Essential Ink Oversized Tee','L',1,1199);
INSERT INTO payments(order_id,method,amount,status,transaction_ref) VALUES (1,'card',1258.95,'paid','SIM-1001');
INSERT INTO reviews(user_id,product_id,rating,review_text) VALUES (1,4,5,'The fabric is substantial and the oversized fit is exactly right.');
